name: webazin
description: Webazin App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  get: ^4.7.3
  get_storage: ^2.1.1
  dio: ^5.11.0
  http: ^1.6.0
  fl_chart: ^1.2.0
  google_fonts: ^8.2.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0


  flutter_svg: ^2.3.0
  flutter_staggered_grid_view: ^0.4.1

  progress_indicators: ^1.0.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  tutorial_coach_mark: ^1.3.4
  video_player: ^2.11.1
  image_picker: ^1.2.3
  fluttertoast: ^8.2.8
  webview_flutter: ^4.14.1
  url_launcher: ^6.3.2
  firebase_messaging: ^16.6.0

  cloud_firestore: ^6.9.0
  firebase_auth: ^6.6.1
  firebase_core: ^4.14.0
  firebase_storage: ^13.5.0
  fluttericon: ^2.0.0
  qr_flutter: ^4.0.0
  flutter_html: ^3.0.0




  persian_datetime_picker: ^3.2.0
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.5
  flutter_fortune_wheel: ^1.3.2
#  socket_io_client: ^2.0.3+1
  socket_io_client: 1.0.2
  sms_autofill: ^2.5.0
  hive: ^2.2.3
  simple_ripple_animation: ^0.0.7
  path_provider: ^2.0.2
  flutter_spinkit: ^5.2.2
  shamsi_date: ^1.1.1
  #  intl: ^0.17.0
#  provider: ^6.0.0
  local_auth: ^3.0.2
#  local_auth_android: ^1.0.15
#  local_auth_ios: ^1.0.10
  #  flutter_windowmanager: ^0.2.0
  #  dio_http_cache: ^0.3.0
  #  connectivity: ^3.0.6
  #  laravel_echo: ^0.2.9
  #  loading: ^1.0.2
  #  flutter_windowmanager: ^0.2.0

  package_info_plus: ^10.2.1
  flutter_easyloading: ^4.0.2
  lottie: ^3.1.2

#  ########################################################







  cupertino_icons: ^1.0.8

  qr_code_scanner:
    path: packages/qr_code_scanner
dependency_overrides:
  quiver: 2.1.5
  csslib: 0.17.3
  html: 0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - config/
    - assets/
    - assets/img/
    - assets/svg/
    - assets/png/
    - assets/icon/
    - assets/logo/
    - assets/locales/
    - assets/my_db.db
    - assets/video/
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf

    - family: Vazir-Bold
      fonts:
        - asset: assets/fonts/Vazir-Bold.ttf

    - family: Vazir-Light
      fonts:
        - asset: assets/fonts/Vazir-Light.ttf

    - family: Vazir-Medium
      fonts:
        - asset: assets/fonts/Vazir-Medium.ttf

    - family: Vazir-Thin
      fonts:
        - asset: assets/fonts/Vazir-Thin.ttf

    - family: IranNastaliq
      fonts:
        - asset: assets/fonts/IranNastaliq.ttf


